# Generated by Django 4.0.4 on 2022-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(),
        ),
    ]
