# Generated by Django 4.0.4 on 2022-04-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomrecipe', '0002_ingredients_instructions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
