# Generated by Django 4.0.4 on 2022-04-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomrecipe', '0003_rename_ingredients_ingredient_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
